### PR TITLE
Deadline -> Due Date

### PR DESCRIPTION
**Pull request by jonafato**

### CODE REVIEW

**Review by kjaymiller — APPROVED** [review]

**Comment by kjaymiller** [comment]
I quickly changed this path so the resolution should be simple

**Comment by kjaymiller** [comment]
Were you waiting to push this? Perhaps for #3

**Comment by jonafato** [comment]
Is #3 something I can fix as part of this change? I'm not sure where that string is actually used / comes from.

**Comment by kjaymiller** [comment]
I believe the URL comes from the the directory name so changing that would change the URL. That said we would need to redeploy the function for changes to happen. Currently I don't have an action to do that so once things are updated I can manually run them.

**Pull request merged**
